# Generated by Django 5.2.6 on 2025-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_headquarters', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=100)),
                ('official_area', models.FloatField()),
                ('type_classification', models.CharField(max_length=50)),
                ('usage_status', models.CharField(max_length=50)),
                ('purpose_2024', models.CharField(blank=True, max_length=100, null=True)),
                ('future_plan', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
