# Generated by Django 5.2.6 on 2025-09-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', '모집중'), ('closed', '완료')], default='open', max_length=10),
        ),
    ]
