# Generated by Django 5.2.6 on 2025-09-11 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제안 제목')),
                ('location', models.CharField(max_length=100, verbose_name='장소')),
                ('content', models.TextField(verbose_name='제안 내용')),
                ('status', models.CharField(choices=[('recruiting', '모집중'), ('completed', '완료')], default='recruiting', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_by', models.ManyToManyField(blank=True, related_name='recommended_proposals', to=settings.AUTH_USER_MODEL, verbose_name='추천한 사용자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
